### ISSUE TITLE
Upgrade Pi4 heat management and case

### ISSUE THREAD

**Issue by 1Copenut** [1Copenut/homelab-learning#163]
## Description and how to
* https://www.youtube.com/watch?v=WMIniPIvYjM

## Tasks
- [x] Flash firmware `sudo apt full-upgrade` should do the trick
- [x] Buy heat sinks
- [x] Buy case and fan

**Comment by 1Copenut** [comment]
Completed on Sunday, August 18th. Just in time for dinner and `Alien: Romulus`.
